SELECT C.car_id
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.car_id=H.car_id
WHERE MONTH(H.start_date)=10 AND C.car_type='세단'
GROUP BY C.CAR_ID
ORDER BY C.car_id DESC